spring:
  application:
    name: portal-demo
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portal-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
  redis:
    host: localhost
    database: 3

server:
  servlet:
    context-path: /portal

mybatis-plus:
  mapper-locations: classpath:mapper/**.xml

